---
- hosts: local
  become: yes
  become_method: sudo

  pre_tasks:
  - name: Append proper hostname entry to /etc/hosts
    lineinfile:
      path: "/etc/hosts"
      line: "{{ server_local_ip }}    {{ server_hostname }}"

  roles:
  - { role: openssl-certs }
  - { role: jupyter-notebook }
  - { role: apache-spark }

