heat_template_version: 2015-04-30


description: |
  Creates and configures a single VM used for teaching tesseract.


parameter_groups:
  - label: VM parameters
    description: Parameters required to orchestrate the VM
    parameters:
    - private_network
    - public_network
    - kp_name
    - server_image
    - server_name
    - server_flavor

  - label: Application parameters
    description: Parameters required to deploy the application
    parameters:
    - do_updates
    - do_upgrades


parameters:
  private_network:
    type: string
    label: Specify the private network used for this instance
    description: Private network name or ID used for this instance
    default: dhsi-cloud_network

  public_network:
    type: string
    label: Specify the public network (west-cloud/east-cloud)
    description: Public network name or ID used for this instance
    default: VLAN3337

  kp_name:
    type: string
    label: Specify an existing key pair
    description: Name of the key pair used for this instance
    default: yoga3pro

  server_image:
    type: string
    label: Specify the image used to create the instance
    description: Name of the image used to create the VM
    default: tesseract4-student-image-201707260758

  server_name:
    type: string
    label: Specify the name of the instance
    description: Name used to identify the VM
    default: tesseract-student-vm

  server_flavor:
    type: string
    label: Specify the VM hardware type for this instance
    description: It is recommended to select a 'p' flavor
    default: c4-15gb-83

  do_updates:
    type: string
    label: Perform software package index updates
    description: (true) to perform updates, otherwise (false)
    default: "true"
    constraints:
      - allowed_values:
        - "true"
        - "false"

  do_upgrades:
    type: string
    label: Perform software package upgrades
    description: (true) to perform upgrades, otherwise (false)
    default: "true"
    constraints:
      - allowed_values:
        - "true"
        - "false"


resources:
  instance_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_network }
      security_groups:
        - default
        - ssh
        - jupyter_ssl

  instance_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      flavor: { get_param: server_flavor }
      image: { get_param: server_image }
      key_name: { get_param: kp_name }
      networks:
        - port: { get_resource: instance_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            hostname: SERVERNAME
            manage_etc_hosts: true
            package_update: DOUPDATES
            package_upgrade: DOUPGRADES
          params:
            SERVERNAME: { get_param: server_name }
            DOUPDATES: { get_param: do_updates }
            DOUPGRADES: { get_param: do_upgrades }

  instance_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      port_id: { get_resource: instance_port }
      floating_network: { get_param: public_network }


outputs:
  public_ip:
    description: Floating IP address used for this server
    value: { get_attr: [ instance_floating_ip, floating_ip_address ] }
