---
# tasks file for jupyter_notebook

- name: Process the Jupyter Notebook config template
  template:
    src: "templates/{{ jupyter_template_name }}"
    dest: "{{ jupyter_config_dest }}"
    backup: yes
    owner: ubuntu
    group: ubuntu

- name: Copy the config .json file (password)
  copy:
    src: "files/{{ jupyter_config_json }}"
    dest: "{{ jupyter_config_home }}/{{ jupyter_config_json }}"
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Create working directory
  file:
    path: "{{ jupyter_workdir }}"
    state: directory
    mode: 0755

- name: Copy systemd service file
  copy:
    src: "files/{{ jupyter_service_file }}"
    dest: "/etc/systemd/system/{{ jupyter_service_file }}"
    owner: root
    group: root
    mode: 0644
  register: service_file

- name: Register the new service
  shell: systemctl daemon-reload
  when: service_file.changed

- name: Enable and start service
  service:
    name: jupyter-notebook
    state: restarted
    enabled: yes

