---
# tasks file for jupyter_notebook

- name: Process the Jupyter Notebook config template
  template:
    src: "templates/{{ jupyter_template_name }}"
    dest: "{{ jupyter_config_dest }}"
    backup: yes
    owner: ubuntu
    group: ubuntu

- name: Copy the config .json file (password)
  copy:
    src: "files/{{ jupyter_config_json }}"
    dest: "{{ jupyter_config_home }}/{{ jupyter_config_json }}"
    owner: ubuntu
    group: ubuntu
    mode: 0600

